import type { PhasegridTheme } from "../theme";

/** Same roles, inverted ground. The signal colours are darkened where they would glare on white. */
export const light: PhasegridTheme = {
  id: "light",
  name: "Light",
  type: "light",
  colors: {
    background: "#fbfbfc",
    foreground: "#16181c",
    card: "#ffffff",
    cardForeground: "#16181c",
    popover: "#ffffff",
    popoverForeground: "#16181c",
    primary: "#16181c",
    primaryForeground: "#ffffff",
    secondary: "#eff0f3",
    secondaryForeground: "#16181c",
    muted: "#eff0f3",
    mutedForeground: "#6b7280",
    accent: "#e4e6eb",
    accentForeground: "#16181c",
    destructive: "#cd2b31",
    destructiveForeground: "#ffffff",
    border: "#dcdfe4",
    input: "#ffffff",
    ring: "#3b5bdb",
    logInfo: "#6b7280",
    logWarn: "#b45309",
    logError: "#cd2b31",
  },
  grid: {
    background: "#f4f5f7",
    gridLine: "#e4e6eb",
    nodeFill: "#ffffff",
    nodeStroke: "#cfd3da",
    nodeSelected: "#3b5bdb",
    knobBody: "#e9ebef",
    knobPointer: "#3a3f47",
    knobLabel: "#6b7280",
    marquee: "#3b5bdb",
    playhead: "#b45309",
    signal: {
      any: "#6b7280",
      audio: "#cd2b31",
      cv: "#c2410c",
      gate: "#a16207",
      pitch: "#b45309",
      phase: "#7c3aed",
      note: "#15803d",
    },
  },
};
